"""change interaction character_id to string

Revision ID: e2d36ce52d0f
Revises: 
Create Date: 2024-12-29 09:08:00.132040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2d36ce52d0f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('character_backstories_character_id_fkey', 'character_backstories', type_='foreignkey')
    op.create_foreign_key(None, 'character_backstories', 'characters', ['character_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'characters', 'users', ['user_id'], ['id'])
    op.drop_constraint('game_states_character_id_fkey', 'game_states', type_='foreignkey')
    op.create_foreign_key(None, 'game_states', 'characters', ['character_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'game_states', 'users', ['user_id'], ['id'])
    op.create_index('ix_interactions_character_id_timestamp', 'interactions', ['character_id', 'timestamp'], unique=False)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index('ix_interactions_character_id_timestamp', table_name='interactions')
    op.drop_constraint(None, 'game_states', type_='foreignkey')
    op.drop_constraint(None, 'game_states', type_='foreignkey')
    op.create_foreign_key('game_states_character_id_fkey', 'game_states', 'characters', ['character_id'], ['id'])
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.drop_constraint(None, 'character_backstories', type_='foreignkey')
    op.create_foreign_key('character_backstories_character_id_fkey', 'character_backstories', 'characters', ['character_id'], ['id'])
    # ### end Alembic commands ###
